// <auto-generated />
using System;
using Book_Store_DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Book_Store_DataAccess.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240926171819_nullablesadded")]
    partial class nullablesadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Book_Store_Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(90)
                        .HasColumnType("nvarchar(90)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Test",
                            DisplayOrder = 1
                        });
                });

            modelBuilder.Entity("Book_Store_Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("List50")
                        .HasColumnType("float");

                    b.Property<double?>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double?>("Price100")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Author = "Harper Lee",
                            CategoryId = 1,
                            Description = "A classic novel about racial injustice in the American South.",
                            ISBN = "9780446310775",
                            ImageUrl = "",
                            List50 = 90.0,
                            ListPrice = 50.0,
                            Price100 = 70.0,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 1,
                            Author = "George Orwell",
                            CategoryId = 1,
                            Description = "A dystopian novel about a totalitarian government.",
                            ISBN = "9780451534856",
                            ImageUrl = "",
                            List50 = 90.0,
                            ListPrice = 50.0,
                            Price100 = 70.0,
                            Title = "1984"
                        });
                });

            modelBuilder.Entity("Book_Store_Models.Product", b =>
                {
                    b.HasOne("Book_Store_Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
